// Static task data for template
export const STATIC_TASKS = [
    {
        id: 1,
        title: "Social Media Strategy",
        description: "Develop Q1 social media strategy for TechCorp",
        assignee: 2,
        assignee_details: {
            id: 2,
            username: "jane_smith",
            first_name: "Jane",
            last_name: "Smith",
            full_name: "Jane Smith",
            designation: "UI/UX Designer",
            department: "Design",
            employee_id: "CP-003",
            role: "employee",
            email: "jane@cipherpeak.com",
            phone_number: "+1987654321",
        },
        client: 1,
        client_details: {
            id: 1,
            client_name: "TechCorp Solutions",
        },
        status: "in_progress",
        status_display: "In Progress",
        priority: "high",
        priority_display: "High",
        task_type: "planning",
        task_type_display: "Planning",
        due_date: "2026-01-10",
        created_at: "2026-01-01T10:00:00Z",
        updated_at: "2026-01-06T10:00:00Z",
        created_by: 1,
        created_by_details: {
            id: 1,
            username: "admin",
            email: "admin@cipherpeak.com",
            first_name: "Admin",
            last_name: "User",
            full_name: "Admin User",
            role: "superuser",
            designation: "Chief Administrator",
            department: "Management",
            employee_id: "CP-001",
            phone_number: "+1234567890",
        },
    },
    {
        id: 2,
        title: "Content Creation",
        description: "Create social media content for Global Retail",
        assignee: 3,
        assignee_details: {
            id: 3,
            username: "mike_wilson",
            first_name: "Mike",
            last_name: "Wilson",
            full_name: "Mike Wilson",
            designation: "Senior Developer",
            department: "Development",
            employee_id: "CP-004",
            role: "employee",
            email: "mike@cipherpeak.com",
            phone_number: "+1555123456",
        },
        client: 2,
        client_details: {
            id: 2,
            client_name: "Global Retail",
        },
        status: "pending",
        status_display: "Pending",
        priority: "medium",
        priority_display: "Medium",
        task_type: "content_creation",
        task_type_display: "Content Creation",
        due_date: "2026-01-15",
        created_at: "2026-01-03T10:00:00Z",
        updated_at: "2026-01-06T10:00:00Z",
        created_by: 1,
        created_by_details: {
            id: 1,
            username: "admin",
            email: "admin@cipherpeak.com",
            first_name: "Admin",
            last_name: "User",
            full_name: "Admin User",
            role: "superuser",
            designation: "Chief Administrator",
            department: "Management",
            employee_id: "CP-001",
            phone_number: "+1234567890",
        },
    },
    {
        id: 3,
        title: "Client Meeting",
        description: "Quarterly review meeting with Creative Agency",
        assignee: 1,
        assignee_details: {
            id: 1,
            username: "admin",
            first_name: "Admin",
            last_name: "User",
            full_name: "Admin User",
            designation: "Chief Administrator",
            department: "Management",
            employee_id: "CP-001",
            role: "superuser",
            email: "admin@cipherpeak.com",
            phone_number: "+1234567890",
        },
        client: 3,
        client_details: {
            id: 3,
            client_name: "Creative Agency",
        },
        status: "scheduled",
        status_display: "Scheduled",
        priority: "high",
        priority_display: "High",
        task_type: "meeting",
        task_type_display: "Meeting",
        due_date: "2026-01-12",
        created_at: "2026-01-05T10:00:00Z",
        updated_at: "2026-01-06T10:00:00Z",
        created_by: 1,
        created_by_details: {
            id: 1,
            username: "admin",
            email: "admin@cipherpeak.com",
            first_name: "Admin",
            last_name: "User",
            full_name: "Admin User",
            role: "superuser",
            designation: "Chief Administrator",
            department: "Management",
            employee_id: "CP-001",
            phone_number: "+1234567890",
        },
    },
];
